sonar.projectKey=travel-itinerary-planner
sonar.projectName=Travel Itinerary Planner
sonar.projectVersion=1.0.0
sonar.sources=airport-service/app,itinerary-service/app
sonar.tests=airport-service/tests,itinerary-service/tests
sonar.python.version=3.11
sonar.sourceEncoding=UTF-8
